export const styles = {
    container: {
        maxWidth: "1400px",
        margin: "0 auto",
        padding: "20px",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    },
    pageHeader: {
        marginBottom: "30px",
        paddingBottom: "20px",
        borderBottom: "2px solid #007bff",
    },
    cardContainer: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
        gap: "20px",
        marginBottom: "30px",
    },
    card: {
        backgroundColor: "#fff",
        border: "1px solid #e0e0e0",
        borderRadius: "8px",
        padding: "20px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        transition: "all 0.3s ease",
        cursor: "pointer",
    },
    cardHover: {
        boxShadow: "0 4px 16px rgba(0,0,0,0.15)",
        transform: "translateY(-2px)",
    },
    button: {
        padding: "12px 24px",
        fontSize: "16px",
        fontWeight: "600",
        border: "none",
        borderRadius: "6px",
        backgroundColor: "#007bff",
        color: "white",
        cursor: "pointer",
        transition: "all 0.3s ease",
    },
    buttonHover: {
        backgroundColor: "#0056b3",
        transform: "scale(1.02)",
    },
    input: {
        width: "100%",
        padding: "12px",
        fontSize: "14px",
        border: "1px solid #ddd",
        borderRadius: "6px",
        boxSizing: "border-box",
        fontFamily: "inherit",
    },
    label: {
        display: "block",
        marginBottom: "8px",
        fontWeight: "600",
        color: "#333",
    },
    select: {
        width: "100%",
        padding: "12px",
        fontSize: "14px",
        border: "1px solid #ddd",
        borderRadius: "6px",
        boxSizing: "border-box",
        fontFamily: "inherit",
    },
    textarea: {
        width: "100%",
        padding: "12px",
        fontSize: "14px",
        border: "1px solid #ddd",
        borderRadius: "6px",
        boxSizing: "border-box",
        fontFamily: "inherit",
        minHeight: "100px",
        resize: "vertical",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
        marginTop: "20px",
        backgroundColor: "white",
        borderRadius: "8px",
        overflow: "hidden",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    },
    tableHeader: {
        backgroundColor: "#f5f5f5",
        fontWeight: "600",
        padding: "15px",
        textAlign: "left",
        borderBottom: "2px solid #ddd",
    },
    tableCell: {
        padding: "15px",
        borderBottom: "1px solid #e0e0e0",
    },
    tableRow: {
        transition: "background-color 0.2s ease",
    },
    badge: {
        display: "inline-block",
        padding: "6px 12px",
        borderRadius: "20px",
        fontSize: "12px",
        fontWeight: "600",
        backgroundColor: "#e0e0e0",
        color: "#333",
    },
    badgeSuccess: {
        backgroundColor: "#d4edda",
        color: "#155724",
    },
    badgeWarning: {
        backgroundColor: "#fff3cd",
        color: "#856404",
    },
    badgeDanger: {
        backgroundColor: "#f8d7da",
        color: "#721c24",
    },
    form: {
        backgroundColor: "white",
        padding: "30px",
        borderRadius: "8px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        maxWidth: "600px",
    },
    formGroup: {
        marginBottom: "20px",
    },
    sidebarLayout: {
        display: "flex",
        gap: "20px",
        minHeight: "calc(100vh - 100px)",
    },
    sidebar: {
        width: "250px",
        backgroundColor: "#2c3e50",
        color: "white",
        padding: "20px",
        borderRadius: "8px",
        height: "fit-content",
        position: "sticky",
        top: "20px",
    },
    sidebarNav: {
        listStyle: "none",
        padding: 0,
        margin: 0,
    },
    sidebarNavItem: {
        padding: "12px 16px",
        cursor: "pointer",
        borderRadius: "6px",
        marginBottom: "8px",
        transition: "all 0.3s ease",
        backgroundColor: "rgba(255,255,255,0.1)",
    },
    sidebarNavItemActive: {
        backgroundColor: "#007bff",
        fontWeight: "600",
    },
    mainContent: {
        flex: 1,
        minWidth: 0,
    },
    tabs: {
        display: "flex",
        gap: "0",
        borderBottom: "2px solid #e0e0e0",
        marginBottom: "30px",
    },
    tab: {
        padding: "15px 25px",
        backgroundColor: "transparent",
        border: "none",
        cursor: "pointer",
        fontWeight: "600",
        color: "#666",
        fontSize: "16px",
        transition: "all 0.3s ease",
        borderBottom: "3px solid transparent",
        marginBottom: "-2px",
    },
    tabActive: {
        color: "#007bff",
        borderBottomColor: "#007bff",
    },
    emptyState: {
        textAlign: "center",
        padding: "60px 20px",
        color: "#999",
        backgroundColor: "#f9f9f9",
        borderRadius: "8px",
        marginTop: "40px",
    },
    errorBox: {
        backgroundColor: "#f8d7da",
        color: "#721c24",
        padding: "15px",
        borderRadius: "6px",
        marginBottom: "20px",
        border: "1px solid #f5c6cb",
    },
    successBox: {
        backgroundColor: "#d4edda",
        color: "#155724",
        padding: "15px",
        borderRadius: "6px",
        marginBottom: "20px",
        border: "1px solid #c3e6cb",
    },
    modal: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
    },
    modalContent: {
        backgroundColor: "white",
        padding: "30px",
        borderRadius: "8px",
        maxWidth: "500px",
        width: "90%",
        maxHeight: "90vh",
        overflowY: "auto",
        boxShadow: "0 4px 20px rgba(0,0,0,0.2)",
    },
};
